# Generated by Django 3.2.25 on 2024-11-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
