# Generated by Django 3.2.25 on 2024-11-01 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_roles_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='equipo',
            field=models.ManyToManyField(blank=True, null=True, related_name='supervisores', to='app.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='Activo', max_length=30),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='supervisor_vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.supervisor'),
        ),
    ]
