# Generated by Django 3.2.25 on 2024-11-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20241101_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='equipo',
            field=models.ManyToManyField(blank=True, related_name='supervisores', to='app.Usuario'),
        ),
    ]
