# Generated by Django 3.2.25 on 2024-11-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_supervisor_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='area',
        ),
    ]
