# Generated by Django 3.2.25 on 2024-11-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_supervisor_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
