# Generated by Django 3.2.25 on 2024-11-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_inventario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(default='Disponible', max_length=30),
        ),
    ]
