# Generated by Django 3.2.25 on 2024-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_inventario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='nro_boleta',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
